name: Auto Merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jhipster/generator-jhipster-micronaut' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.4.0
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
        if: steps.dependabot-metadata.outputs.dependency-names == 'io.micronaut.platform:micronaut-platform'
      - uses: jhipster/actions/setup-git@v0
        if: steps.dependabot-metadata.outputs.dependency-names == 'io.micronaut.platform:micronaut-platform'
      - name: download bom
        run: |
          wget -O micronaut-platform.pom https://repo1.maven.org/maven2/io/micronaut/platform/micronaut-platform/${{ steps.dependabot-metadata.outputs.new-version }}/micronaut-platform-${{ steps.dependabot-metadata.outputs.new-version }}.pom
          git add .
          git commit -a -m "update micronaut-platform bom to v${{ steps.dependabot-metadata.outputs.new-version }}"
          git push -u origin
        working-directory: generators/micronaut/resources
        if: steps.dependabot-metadata.outputs.dependency-names == 'io.micronaut.platform:micronaut-platform'
